name: DEPLOY
on:
  push:
    branches:
      - 'main'
      - 'deployment'
  workflow_dispatch:  

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v3
        with:
          context: ./backen-dotnet
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hr-backend:latest

      - name: Build and Push mssql Image
        uses: docker/build-push-action@v3
        with:
          context: ./mssql
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mssql-backend:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend-project
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hr-frontend:latest
          
      - name: Build and Push flask Image
        uses: docker/build-push-action@v3
        with:
          context: ./flaskProject1
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hr-flask:latest

  deploy:
    name: Deploy to Server with Ansible
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          PRIVE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook to Deploy
        run: ansible-playbook -i ansible/inventory.ini ansible/deploy-playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'